### ISSUE TITLE
Notifications not disapear after custom time (eg. since 12s.).

### ISSUE THREAD

**Issue by SzykCech4** [KaOSx/main#47] opened 2019-10-23 18:34 UTC
#### Submission type

  - [ ] Bug report

#### Package name & version you are having issues with or have a request for

> Ustawienia systemowe Wersja 5.17.0

#### Used repositories

> ?

#### Expected behaviour

> Notifications should disapear after time specified in KDE Settings.

#### Actual behaviour

> Some of them remain visible for ever (at least this is true for Krusader).

#### Steps to reproduce the problem

> Open KDE Settings->Notifications->Hide after
> Set 12s.
> Run Krusader
> Try delete some file which not exist. You can do this very easy: select file click delete, and confirm, and click delete again and confirm again. This is very slowly operation for Krusader (I don't know why).
![Screenshot_20191023_202505](https://user-images.githubusercontent.com/44374677/67423538-bd575580-f5d4-11e9-9a73-eeac5b600c03.png)

This is probably KDE bug because I feel have the same problem on my previous os-es (in home: KDE Neon and Kubuntu, and at work Debian). I feel so nervous so I disable KDE notifications in options entirely.

#### System info link created by Octopi > Tools > SysInfo

> 
[octopi-sysinfo-2052296094.log](https://github.com/KaOSx/main/files/3763893/octopi-sysinfo-2052296094.log)

**Comment by SzykCech4** [comment] 2019-10-23 19:29
I add new user to my system. But I can't reproduce this behaviour. Even more! Krusader file operations are very fast. I have no idea what I did wrong - seems some option combinations works badly.
Any way: If you are motivated enough I can send you some of my ~./.config/* files. Maybe this will help.

**Comment by demmm** [comment] 2019-10-23 19:54
Not a bug thus.  Bug reports are not for helping, you can join in IRC #kaosx or in the forum to get help with rc files issues in your users home directory.
Closing.

**Closed by demmm** 2019-10-23 19:54 UTC
