### ISSUE TITLE
black screen after update

### ISSUE THREAD

**Issue by mcirsta** [KaOSx/main#15] opened 2015-09-13 14:05 UTC
I installed KaOS 2015.08 and then did a pacman -Suy to update to the latest on 13.09.2015. The update seems to have gone well and no erorrs were reported but right at the end of it KDE crashed. I then just rebooted and the boot took longe than expected.
 I have auto login and all I got after the reboot was a blank screen with just the top left corner KDE menu showing. Ctrl+Alt+Del also worked at first presenting me with the option to logout... which didn't do much. I then went into the command line with ctl+alt+F2 and did a rm -rf on .local and .kde4 folders from my home dir. After typing reboot everything now works fine as expected. I suspect the problem was with KDE and some of it's config ... it's not the first time KDE config breaks after a KDE bump ... but I didn't mess with any of the KDE config since I had just installed the OS.

**Comment by demmm** [comment] 2015-09-13 19:53
System updates do not touch the users /home directory, so if removing files from your /home fixes it, then this looks like an issue with installing over an existing old /home or user adding non-supported widget/plasmoid/theme/icon-set.

**Comment by mcirsta** [comment] 2015-09-13 20:58
I'm pretty sure all I did was:

1. Install 
2. Do the updates

 I know system updates do not touch the /home, the problem is that part of the settings created there in home by the initial KDE wersion was not to the liking of the updates KDE version which resulted in KDE plasma displaying a broken bland screen.
  It's not the first time I've had this happen with KDE which is why I knew how to workaround it.
 The test system was a laptop with Intel graphics, Acer Aspire One 756 with a Celeron Dual-Core 877

**Comment by demmm** [comment] 2015-09-13 21:13
"Pretty sure" is hard to use in a bug report :)
Logs are needed, plus info how to reproduce, test installs + updates on test installs are done constantly here, one system is quite similar to what is mentioned here, intel gfx, and dual core celeron, never seen this issue on that system
Best get logs next time, if you feel like trying to reproduce:
http://kaosx.us/asking-and-reporting-the-smart-way/
Plus when you reboot into a black screen again, make sure to get /var/log/Xorg.0.log, plus ~/.xsession-errors, besides the journalctl logs explained in the link above.

**Comment by mcirsta** [comment] 2015-09-13 22:30
Yeah second time around it worked just fine but I'm sure I didn't do anything fancy the first time either... gives me great confidence in the new KDE ... random bugs are the best.

 I think it was the KDE crash during the last part of the update that did this ... This time around there was no crash at the end of pacman -Suy so yeah...

 Better close this one I guess, it was most likely an upstream issue and let's hope the new plasma stabilizes.

 Othern than this it was a nice experience with KaOS ... maybe in the future something to automatically collect traces ( command line so that it will work for these cases too ) fonts also looked a bit small but that's not a biggie.

**Comment by demmm** [comment] 2015-09-30 22:42
Closing as per submitter request.

**Closed by demmm** 2015-09-30 22:42 UTC
